services:
  db:
    build:
      context: ./Database
    ports:
      - "3308:3306"
    volumes:
      - "./Database/mariadb:/var/lib/mysql:z"
      - "./Database/init.sql:/docker-entrypoint-initdb.d/init.sql"
  frontend:
    build:
      context: ./Frontend
    ports: 
      - "3000:3000"
  backend:
    build:
      context: ./Backend
    ports:
      - "5050:5050"
    volumes:
      - "./Backend/cron/volume/base_crontab:/var/spool/cron/crontabs/root"
      - "./Backend/cron/volume/disk_cleaner.sh:/app/disk_cleaner.sh"
      - "./Backend/cron/volume/cron.log:/var/log/cron.log"
    depends_on:
      - db
    restart: unless-stopped
