services:
  db:
    build:
      context: ./Database
    ports:
      - "3308:3306"
    volumes:
      - "./Database/mariadb:/var/lib/mysql:z"
      - "./Database/init.sql:/docker-entrypoint-initdb.d/init.sql"
  frontend:
    build:
      context: ./Frontend
    ports: 
      - "3000:3000"
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
